const $=id=>document.getElementById(id);
const setup=$('setup'), terminal=$('terminal'), qrView=$('qrView'), promptpay=$('promptpay'), amount=$('amount'), qr=$('qr'), status=$('status'), payAmount=$('payAmount');
const saved=localStorage.getItem('promptpay_id'); if(saved){promptpay.value=saved; setup.classList.add('hidden'); terminal.classList.remove('hidden');}
$('save').onclick=()=>{const id=promptpay.value.replace(/[-\s]/g,''); if(!/^\d{10}$|^\d{13}$|^\d{15}$/.test(id)) return alert('กรุณาใส่เลขพร้อมเพย์ให้ถูกต้อง'); localStorage.setItem('promptpay_id',id); setup.classList.add('hidden'); terminal.classList.remove('hidden');};
$('settingsBtn').onclick=()=>{setup.classList.remove('hidden');terminal.classList.toggle('hidden');qrView.classList.add('hidden');};
const keys=['7','8','9','4','5','6','1','2','3','00','0','⌫']; keys.forEach(k=>{const b=document.createElement('button');b.textContent=k;b.onclick=()=>{if(k==='⌫') amount.value=amount.value.slice(0,-1);else{if(amount.value==='0.00') amount.value='';amount.value+=k;}};$('keys').appendChild(b)});
$('make').onclick=async()=>{const id=localStorage.getItem('promptpay_id');const n=Number(amount.value.replace(/,/g,'')); if(!id) return $('settingsBtn').click(); if(!Number.isFinite(n)||n<=0) return alert('กรุณาระบุจำนวนเงิน'); $('make').disabled=true;$('make').textContent='กำลังสร้าง QR...'; try{const r=await fetch('/api/qr',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({promptpayId:id,amount:n})});const text=await r.text();let d;try{d=JSON.parse(text)}catch{throw new Error(`API ตอบกลับไม่ถูกต้อง (HTTP ${r.status})`)} if(!r.ok||!d.ok) throw new Error(d.error||'สร้าง QR ไม่สำเร็จ'); qr.src=d.qr;payAmount.textContent='฿'+d.amount.toLocaleString('th-TH',{minimumFractionDigits:2});status.textContent='รอลูกค้าชำระเงิน';status.className='status waiting';terminal.classList.add('hidden');qrView.classList.remove('hidden');}catch(e){alert(e.message)}finally{$('make').disabled=false;$('make').textContent='สร้าง QR รับเงิน';}};
$('newPay').onclick=()=>{qrView.classList.add('hidden');terminal.classList.remove('hidden');status.className='status waiting'};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(amount.value);$('copy').textContent='คัดลอกแล้ว ✓';setTimeout(()=>$('copy').textContent='คัดลอกยอดเงิน',1200)}catch{}};
